language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - composer global require fabpot/php-cs-fixer dev-master

script:
  - php-cs-fixer fix --dry-run
